apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: LoadBalancer  # Exposes the service externally using a cloud provider's load balancer
  ports:
  - port: 80  # The port the service is exposed on
    targetPort: 80  # The target port on the container
    protocol: TCP
  selector:
    app: fastapi
